CREATE TABLE IF NOT EXISTS test_runs (
    run_id VARCHAR(64) PRIMARY KEY,
    suite_name VARCHAR(64) NOT NULL,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(32) NOT NULL
);
